version: '3'

services:

  message-queue:
    image: nats:linux
    networks:
      - ms-net

  megastore.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - db-credentials.env
    ports:
      - "80"

  megastore.savesalehandler:
    env_file:
      - db-credentials.env

networks:
  default:
    external:
      name: nat
