version: '3.5'

services:

  message-queue:
    image: nats:linux
    networks:
      - ms-net

  megastore.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
      - APP_INSIGHTS_INSTRUMENTATION_KEY=fba89ed9-b023-48f0-a7bb-6279ba6b5c87
    ports:
      - 80
    depends_on:
      - message-queue
    networks:
      - ms-net

  megastore.savesalehandler:
    environment:
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
      - APP_INSIGHTS_INSTRUMENTATION_KEY=fba89ed9-b023-48f0-a7bb-6279ba6b5c87
    env_file:
      - db-credentials.env
    depends_on:
      - message-queue
    networks:
      - ms-net

networks:
  ms-net: