apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: megastore-savesalehandler-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: megastore-savesalehandler
    spec:
      containers:
      - name: megastoresavesalehandler
        env:
        - name: MESSAGE_QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: message.queue
              key: MESSAGE_QUEUE_URL
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: db.connection
              key: DB_CONNECTION_STRING
        image: prmcr.azurecr.io/megastoresavehandler
        imagePullPolicy: Always
      imagePullSecrets:
        - name: prmcrauth