apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: message-queue-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: message-queue
    spec:
      containers:
      - name: messagequeue
        image: nats:linux
        resources:
          requests:
            cpu: 500m
            memory: 2000Mi
          limits:
            cpu: 500m
            memory: 2000Mi        
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor